server_port: 8080
postgresql_user: 'postgres'
password: '1234'
postgresql_host: 'localhost'
dbname: 'postgres'
db_schema: 'matrix'
db_path_name: '../data/data_bases.json'
table_partition_size: 7
data_generation_dir_path: '../data_base_generation'
categories_count: 61