{
 "title": "Calculus Enjoyers Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Price Retriever RPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(price_retriever_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Price Manager RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(price_manager_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Price Manager Request Duration Buckets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(price_manager_request_duration_seconds_bucket[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Price Retriever Request Duration Buckets",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(price_retriever_request_duration_seconds_bucket[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Misses Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 * (rate(price_retriever_cache_misses_total[1m]) / rate(price_retriever_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}